language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - "node"
  - "5"
  - "4"
before_install:
  # install wine
  - sudo add-apt-repository -y ppa:wine/wine-builds && sudo apt-get update && sudo apt-get install -y --install-recommends winehq-devel
install:
  - npm run dev-up
script:
  - npm run ci
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
addons:
  code_climate:
    repo_token: CODE_CLIMATE_TOKEN
